// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7O18JUZQAbsOoCkr2mwy-itIoA-sDFw',
    appId: '1:743932954595:web:988c61c9047cc6da1142d6',
    messagingSenderId: '743932954595',
    projectId: 'bookswap-e16a0',
    authDomain: 'bookswap-e16a0.firebaseapp.com',
    databaseURL: 'https://bookswap-e16a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookswap-e16a0.firebasestorage.app',
    measurementId: 'G-0CZ7LW0263',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSTCXaa9JeMmIuPgv4iBf_d7tDe8unAI',
    appId: '1:743932954595:android:027ebc2ff7c68b631142d6',
    messagingSenderId: '743932954595',
    projectId: 'bookswap-e16a0',
    databaseURL: 'https://bookswap-e16a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookswap-e16a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpWclsu7pB3Em9kymCRyS0sXUWEpioy0',
    appId: '1:743932954595:ios:26e86247c1a8f1251142d6',
    messagingSenderId: '743932954595',
    projectId: 'bookswap-e16a0',
    databaseURL: 'https://bookswap-e16a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookswap-e16a0.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpWclsu7pB3Em9kymCRyS0sXUWEpioy0',
    appId: '1:743932954595:ios:26e86247c1a8f1251142d6',
    messagingSenderId: '743932954595',
    projectId: 'bookswap-e16a0',
    databaseURL: 'https://bookswap-e16a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookswap-e16a0.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI7O18JUZQAbsOoCkr2mwy-itIoA-sDFw',
    appId: '1:743932954595:web:6493c7655c3e6c2b1142d6',
    messagingSenderId: '743932954595',
    projectId: 'bookswap-e16a0',
    authDomain: 'bookswap-e16a0.firebaseapp.com',
    databaseURL: 'https://bookswap-e16a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookswap-e16a0.firebasestorage.app',
    measurementId: 'G-L7YCBPGX61',
  );
}
